services:
  mms-server:
    build: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_URL=${REDIS_URL}
      - SERVER_PORT=${SERVER_PORT}
    command: sh -c "sleep 5 && ./mms-migrate && ./mms-server"
  
  mms-client:
    build: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - mms-server
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
  
  postgres:
    image: postgres:14
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  rabbitmq:
    image: rabbitmq:3.11
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672" # management UI
    env_file:
      - .env
  
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
