version: '3.8'
services:
  mms-client:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app:cached
      - /app/node_modules
    
    command: sh -c "npm run dev -- --host 0.0.0.0 --port $CLIENT_PORT"